# Socket configurations
network: tcp
host: 127.0.0.1
port: 5000

# Handler configurations
directory: .
mime: text/plain; charset=UTF-8
methods:
  - GET
  - HEAD
executables:
  cat:
    - --help
  grep:
    - --help
  ls:
    - --help

# Server configurations
read: 5
write: 5
idle: 60
ca_certificate: ssl/ca_certs/ca.crt
server_certificate: ssl/server_certs/server.crt
server_key: ssl/server_certs/server.key
