# Socket
network = "tcp"
host = "127.0.0.1"
port = "5000"

# Handler
directory = "."
mime = "text/plain; charset=UTF-8"
methods = ["GET", "HEAD"]

[executables]
cat = ["--help"]
grep = ["--help"]
ls = ["--help"]

# Server
read = 5
write = 5
idle = 60
